<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <NoWarn>$(NoWarn);xUnit1051</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Penghou.Siming.Cryptography\Penghou.Siming.Cryptography.csproj" />
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Penghou.Siming\Penghou.Siming.csproj" />
    <ProjectReference Include="..\..\src\Penghou.Siming.Testing\Penghou.Siming.Testing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\vectors\guyabano-canonical-json-v2.json" Link="vectors\guyabano-canonical-json-v2.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\vectors\penghou-canonical-json-v2.json" Link="vectors\penghou-canonical-json-v2.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
