<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Penghou.Siming\Penghou.Siming.csproj" />
    <ProjectReference Include="..\Penghou.Siming.Cryptography\Penghou.Siming.Cryptography.csproj" />
    <ProjectReference Include="..\Penghou.Siming.Sqlite\Penghou.Siming.Sqlite.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
